package core.structure.description

object DescriptionParameters {
  const val structure = "structure"
  const val definition = "def"
  const val name = "name"
  const val repeat = "repeat"
  const val all = "all"
  const val type = "type"
  const val medium = "medium"
  const val particles = "particles"
  const val exciton = "exciton"
  const val material = "material"
  const val orders = "orders"
  const val oscillators = "oscillators"
  const val latticeFactor = "lattice_factor"
  const val eps = "eps"
  const val epsInf = "eps_inf"
  const val d = "d"
  const val n = "n"
  const val dampingFactor = "df"
  const val cAl = "cal"
  const val cAs = "cas"
  const val w = "w"
  const val w0 = "w0"
  const val g = "g"
  const val g0 = "g0"
  const val wb = "wb"
  const val gb = "gb"
  const val b = "b"
  const val c = "c"
  const val f = "f"
  const val r = "r"
  const val expr = "expr"
  const val external = "external"

  const val valExprKw = "val"
  const val varExprKw = "var"
  const val funExprKw = "fun"
  const val returnExprKw = "return"
  const val exprLeftKwBoundary = "@"
  const val exprRightKwBoundary = "#"
}